# Dependencies
markdown:         redcarpet
highlighter:      pygments
# Permalinks
permalink:        /blog/:year/:month/:day/:title/
relative_permalinks: true

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format:      '%-d %B %Y'

# Setup
title:            zacharylew.is
tagline:          'The personal website of Zachary Lewis.'
description:      'The personal website of Zachary Lewis. Updated sometimes with discussions on software, user interface and lifestyle design.'
url:              http://zacharylew.is
baseurl:          /

author:
  name:           'Zachary Lewis'
  url:            https://twitter.com/zachwlewis
  email:          contact@zacharylew.is

# Pagination
paginate:         5
pagination_dir:   "/blog/page/:num/"  # Directory base for pagination URLs eg. /blog/page/2/

# Post Excerpts
excerpt_link:     'More &rarr;'  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: ''

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zachwlewis/zachwlewis.github.io
