# The name of the author of the site.
author: Zachary Lewis

# The URL where the site is hosted.
url: http://zacharylew.is

# The title of the site.
title: zacharylew.is

# Permalink settings
permalink: /blog/:year/:month/:day/:title/

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%-d %B %Y"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: contact@zacharylew.is

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "More &rarr;"  # "Continue reading" link text at the bottom of excerpted articles