const item_list = {
  "seeker-m": {
    title: "Seeker's Mask",
    ingredients: ["fool-wm", "judgment-wm"],
    type: "mask",
  },
  "magicseeker-m": {
    title: "Magic Seeker's Mask",
    ingredients: ["fool-wm", "magician-wm"],
    type: "mask",
  },
  "soulhacker-m": {
    title: "Soul Hacker's Mask",
    ingredients: ["magicseeker-m", "seeker-m"],
    type: "mask",
  },
  "mage-m": {
    title: "Mage's Mask",
    ingredients: ["magician-wm", "moon-wm"],
    type: "mask",
  },
  "wizard-m": {
    title: "Wizard's Mask",
    ingredients: ["magician-wm", "priestess-wm"],
    type: "mask",
  },
  "elementalist-m": {
    title: "Elementalist's Mask",
    ingredients: ["wizard-m", "mage-m"],
    type: "mask",
  },
  "warlock-m": {
    title: "Warlock's Mask",
    ingredients: ["wizard-m", "hermit-wm"],
    type: "mask",
  },
  "warrior-m": {
    title: "Warrior's Mask",
    ingredients: ["chariot-wm", "strength-wm"],
    type: "mask",
  },
  "swordmaster-m": {
    title: "Swordmaster's Mask",
    ingredients: ["chariot-wm", "emperor-wm"],
    type: "mask",
  },
  "samurai-m": {
    title: "Samurai's Mask",
    ingredients: ["swordmaster-m", "warrior-m"],
    type: "mask",
  },
  "knight-m": {
    title: "Knight's Mask",
    ingredients: ["hierophant-wm", "strength-wm"],
    type: "mask",
  },
  "mageknight-m": {
    title: "Mage Knight's Mask",
    ingredients: ["hierophant-wm", "justice-wm"],
    type: "mask",
  },
  "paladin-m": {
    title: "Paladin's Mask",
    ingredients: ["mageknight-m", "knight-m"],
    type: "mask",
  },
  "darkknight-m": {
    title: "Dark Knight's Mask",
    ingredients: ["mageknight-m", "hangedman-wm"],
    type: "mask",
  },
  "brawler-m": {
    title: "Brawler's Mask",
    ingredients: ["strength-wm", "sun-wm"],
    type: "mask",
  },
  "pugilist-m": {
    title: "Pugilist's Mask",
    ingredients: ["strength-wm", "justice-wm"],
    type: "mask",
  },
  "martialartist-m": {
    title: "Martial Artist's Mask",
    ingredients: ["pugilist-m", "brawler-m"],
    type: "mask",
  },
  "healer-m": {
    title: "Healer's Mask",
    ingredients: ["lovers-wm", "priestess-wm"],
    type: "mask",
  },
  "cleric-m": {
    title: "Cleric's Mask",
    ingredients: ["lovers-wm", "temperance-wm"],
    type: "mask",
  },
  "saviour-m": {
    title: "Saviour's Mask",
    ingredients: ["cleric-m", "healer-m"],
    type: "mask",
  },
  "gunner-m": {
    title: "Gunner's Mask",
    ingredients: ["hermit-wm", "chariot-wm"],
    type: "mask",
  },
  "sniper-m": {
    title: "Sniper's Mask",
    ingredients: ["hermit-wm", "moon-wm"],
    type: "mask",
  },
  "dragoon-m": {
    title: "Dragoon's Mask",
    ingredients: ["sniper-m", "gunner-m"],
    type: "mask",
  },
  "thief-m": {
    title: "Thief's Mask",
    ingredients: ["hangedman-wm", "tower-wm"],
    type: "mask",
  },
  "assassin-m": {
    title: "Assassin's Mask",
    ingredients: ["hangedman-wm", "devil-wm"],
    type: "mask",
  },
  "ninja-m": {
    title: "Ninja's Mask",
    ingredients: ["assassin-m", "thief-m"],
    type: "mask",
  },
  "faker-m": {
    title: "Faker's Mask",
    ingredients: ["star-wm", "fortune-wm"],
    type: "mask",
  },
  "trickster-m": {
    title: "Trickster's Mask",
    ingredients: ["faker-m", "fool-wm"],
    type: "mask",
  },
  "commander-m": {
    title: "Commander's Mask",
    ingredients: ["emperor-wm", "tower-wm"],
    type: "mask",
  },
  "general-m": {
    title: "General's Mask",
    ingredients: ["emperor-wm", "judgment-wm"],
    type: "mask",
  },
  "warlord-m": {
    title: "Warlord's Mask",
    ingredients: ["general-m", "commander-m"],
    type: "mask",
  },
  "merchant-m": {
    title: "Merchant's Mask",
    ingredients: ["fortune-wm", "temperance-wm"],
    type: "mask",
  },
  "tycoon-m": {
    title: "Tycoon's Mask",
    ingredients: ["merchant-m", "star-wm"],
    type: "mask",
  },
  "summoner-m": {
    title: "Summoner's Mask",
    ingredients: ["devil-wm", "empress-wm"],
    type: "mask",
  },
  "devilsummoner-m": {
    title: "Devil Summoner's Mask",
    ingredients: ["summoner-m", "devil-wm"],
    type: "mask",
  },
  "berserker-m": {
    title: "Berserker's Mask",
    ingredients: ["death-wm", "chariot-wm"],
    type: "mask",
  },
  "destroyer-m": {
    title: "Destroyer's Mask",
    ingredients: ["berserker-m", "tower-wm"],
    type: "mask",
  },
  "dancer-m": {
    title: "Dancer's Mask",
    ingredients: ["fortune-wm", "star-wm", "judgment-wm"],
    type: "mask",
  },
  "mend-m": {
    title: "Mend Mask",
    ingredients: ["justice-wm", "hierophant-wm", "temperance-wm"],
    type: "mask",
  },
  "mind-m": {
    title: "Mind Mask",
    ingredients: ["magician-wm", "sun-wm", "moon-wm"],
    type: "mask",
  },
  "muscle-m": {
    title: "Muscle Mask",
    ingredients: ["chariot-wm", "strength-wm", "emperor-wm"],
    type: "mask",
  },
  "mercy-m": {
    title: "Mercy Mask",
    ingredients: ["lovers-wm", "priestess-wm", "empress-wm"],
    type: "mask",
  },
  "fool-wm": { title: "Fool White Mask", ingredients: [], type: "white mask" },
  "judgment-wm": {
    title: "Judgment White Mask",
    ingredients: [],
    type: "white mask",
  },
  "magician-wm": {
    title: "Magician White Mask",
    ingredients: [],
    type: "white mask",
  },
  "moon-wm": { title: "Moon White Mask", ingredients: [], type: "white mask" },
  "priestess-wm": {
    title: "Priestess White Mask",
    ingredients: [],
    type: "white mask",
  },
  "hermit-wm": {
    title: "Hermit White Mask",
    ingredients: [],
    type: "white mask",
  },
  "chariot-wm": {
    title: "Chariot White Mask",
    ingredients: [],
    type: "white mask",
  },
  "strength-wm": {
    title: "Strength White Mask",
    ingredients: [],
    type: "white mask",
  },
  "emperor-wm": {
    title: "Emperor White Mask",
    ingredients: [],
    type: "white mask",
  },
  "hierophant-wm": {
    title: "Hierophant White Mask",
    ingredients: [],
    type: "white mask",
  },
  "justice-wm": {
    title: "Justice White Mask",
    ingredients: [],
    type: "white mask",
  },
  "hangedman-wm": {
    title: "Hanged Man White Mask",
    ingredients: [],
    type: "white mask",
  },
  "sun-wm": { title: "Sun White Mask", ingredients: [], type: "white mask" },
  "lovers-wm": {
    title: "Lovers White Mask",
    ingredients: [],
    type: "white mask",
  },
  "temperance-wm": {
    title: "Temperance White Mask",
    ingredients: [],
    type: "white mask",
  },
  "tower-wm": {
    title: "Tower White Mask",
    ingredients: [],
    type: "white mask",
  },
  "devil-wm": {
    title: "Devil White Mask",
    ingredients: [],
    type: "white mask",
  },
  "star-wm": { title: "Star White Mask", ingredients: [], type: "white mask" },
  "fortune-wm": {
    title: "Fortune White Mask",
    ingredients: [],
    type: "white mask",
  },
  "empress-wm": {
    title: "Empress White Mask",
    ingredients: [],
    type: "white mask",
  },
  "death-wm": {
    title: "Death White Mask",
    ingredients: [],
    type: "white mask",
  },
};

const sort_order = [
  "seeker-m",
  "magicseeker-m",
  "soulhacker-m",
  "mage-m",
  "wizard-m",
  "elementalist-m",
  "warlock-m",
  "warrior-m",
  "swordmaster-m",
  "samurai-m",
  "knight-m",
  "mageknight-m",
  "paladin-m",
  "darkknight-m",
  "brawler-m",
  "pugilist-m",
  "martialartist-m",
  "healer-m",
  "cleric-m",
  "saviour-m",
  "gunner-m",
  "sniper-m",
  "dragoon-m",
  "thief-m",
  "assassin-m",
  "ninja-m",
  "faker-m",
  "trickster-m",
  "commander-m",
  "general-m",
  "warlord-m",
  "merchant-m",
  "tycoon-m",
  "summoner-m",
  "devilsummoner-m",
  "berserker-m",
  "destroyer-m",
  "dancer-m",
  "mend-m",
  "mind-m",
  "muscle-m",
  "mercy-m",
  "fool-wm",
  "judgment-wm",
  "magician-wm",
  "moon-wm",
  "priestess-wm",
  "hermit-wm",
  "chariot-wm",
  "strength-wm",
  "emperor-wm",
  "hierophant-wm",
  "justice-wm",
  "hangedman-wm",
  "sun-wm",
  "lovers-wm",
  "temperance-wm",
  "tower-wm",
  "devil-wm",
  "star-wm",
  "fortune-wm",
  "empress-wm",
  "death-wm",
];
