const dish_data = [
  {
    dish: "Poached Egg",
    course: "appetizer",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 2,
      western: 5,
      fish: 3,
      meat: 2,
      vegetable: 1,
      sweet: 4,
      spicy: 1,
      neutral: 3,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Miso Soup",
    course: "appetizer",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 5,
      western: 2,
      fish: 4,
      meat: 2,
      vegetable: 3,
      sweet: 2,
      spicy: 2,
      neutral: 3,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Fried Egg",
    course: "appetizer",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 4,
      western: 3,
      fish: 3,
      meat: 3,
      vegetable: 3,
      sweet: 4,
      spicy: 2,
      neutral: 4,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Spinach Quiche",
    course: "appetizer",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 1,
      japanese: 1,
      western: 4,
      fish: 3,
      meat: 3,
      vegetable: 5,
      sweet: 3,
      spicy: 1,
      neutral: 2,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Apple Cider Soda",
    course: "appetizer",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 2,
      western: 4,
      fish: 2,
      meat: 2,
      vegetable: 2,
      sweet: 4,
      spicy: 2,
      neutral: 2,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Coconut Water",
    course: "appetizer",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 3,
      western: 3,
      fish: 2,
      meat: 3,
      vegetable: 3,
      sweet: 5,
      spicy: 1,
      neutral: 3,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Marinated Seafood",
    course: "appetizer",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 3,
      western: 3,
      fish: 5,
      meat: 3,
      vegetable: 4,
      sweet: 2,
      spicy: 3,
      neutral: 3,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Omelet",
    course: "appetizer",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 3,
      western: 4,
      fish: 3,
      meat: 3,
      vegetable: 5,
      sweet: 4,
      spicy: 1,
      neutral: 3,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Pot-au-feu",
    course: "appetizer",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 2,
      western: 4,
      fish: 2,
      meat: 3,
      vegetable: 5,
      sweet: 2,
      spicy: 3,
      neutral: 3,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Tiger Salad",
    course: "appetizer",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 5,
      japanese: 3,
      western: 2,
      fish: 2,
      meat: 1,
      vegetable: 4,
      sweet: 1,
      spicy: 4,
      neutral: 2,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Chopan Salad",
    course: "appetizer",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 2,
      western: 2,
      fish: 2,
      meat: 1,
      vegetable: 5,
      sweet: 3,
      spicy: 5,
      neutral: 2,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Gazpacho",
    course: "appetizer",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 1,
      japanese: 2,
      western: 4,
      fish: 2,
      meat: 2,
      vegetable: 4,
      sweet: 2,
      spicy: 1,
      neutral: 3,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Vegetable Milk Soup",
    course: "appetizer",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 4,
      western: 3,
      fish: 2,
      meat: 2,
      vegetable: 5,
      sweet: 2,
      spicy: 2,
      neutral: 3,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Vegetable Juice",
    course: "appetizer",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 4,
      western: 3,
      fish: 2,
      meat: 2,
      vegetable: 5,
      sweet: 3,
      spicy: 1,
      neutral: 3,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Spicy Pig's Ear",
    course: "appetizer",
    difficulty: "D",
    surprise: true,
    rating: {
      chinese: 4,
      japanese: 3,
      western: 1,
      fish: 1,
      meat: 5,
      vegetable: 2,
      sweet: 1,
      spicy: 5,
      neutral: 5,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },

  {
    dish: "Black Tea Cookies",
    course: "dessert",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 1,
      western: 5,
      fish: 1,
      meat: 1,
      vegetable: 1,
      sweet: 5,
      spicy: 1,
      neutral: 4,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Pancakes",
    course: "dessert",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 1,
      japanese: 2,
      western: 5,
      fish: 1,
      meat: 1,
      vegetable: 1,
      sweet: 5,
      spicy: 1,
      neutral: 4,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Jelly Beans",
    course: "dessert",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 1,
      japanese: 2,
      western: 3,
      fish: 1,
      meat: 2,
      vegetable: 1,
      sweet: 3,
      spicy: 1,
      neutral: 3,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Lemon Honey Pickles",
    course: "dessert",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 1,
      western: 5,
      fish: 1,
      meat: 3,
      vegetable: 3,
      sweet: 5,
      spicy: 1,
      neutral: 4,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Steamed Bread",
    course: "dessert",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 2,
      western: 4,
      fish: 1,
      meat: 1,
      vegetable: 1,
      sweet: 4,
      spicy: 1,
      neutral: 3,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Lollipop",
    course: "dessert",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 1,
      western: 4,
      fish: 1,
      meat: 3,
      vegetable: 1,
      sweet: 5,
      spicy: 1,
      neutral: 3,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Pavlova",
    course: "dessert",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 1,
      japanese: 1,
      western: 5,
      fish: 1,
      meat: 2,
      vegetable: 2,
      sweet: 5,
      spicy: 1,
      neutral: 4,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Sugar Toast",
    course: "dessert",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 2,
      western: 4,
      fish: 1,
      meat: 2,
      vegetable: 1,
      sweet: 5,
      spicy: 1,
      neutral: 3,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Baumkuchen",
    course: "dessert",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 1,
      western: 5,
      fish: 1,
      meat: 2,
      vegetable: 1,
      sweet: 4,
      spicy: 1,
      neutral: 4,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Colorful Macarons",
    course: "dessert",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 1,
      western: 4,
      fish: 1,
      meat: 2,
      vegetable: 1,
      sweet: 5,
      spicy: 2,
      neutral: 3,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Pretzel",
    course: "dessert",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 1,
      western: 4,
      fish: 1,
      meat: 2,
      vegetable: 1,
      sweet: 4,
      spicy: 2,
      neutral: 3,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Baked Flan",
    course: "dessert",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 1,
      western: 5,
      fish: 1,
      meat: 3,
      vegetable: 1,
      sweet: 5,
      spicy: 1,
      neutral: 3,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Cheese on Crackers",
    course: "dessert",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 2,
      western: 5,
      fish: 1,
      meat: 3,
      vegetable: 2,
      sweet: 5,
      spicy: 1,
      neutral: 4,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Spiced Coffee",
    course: "dessert",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 4,
      japanese: 3,
      western: 5,
      fish: 1,
      meat: 3,
      vegetable: 1,
      sweet: 3,
      spicy: 4,
      neutral: 2,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Mint Chip Ice Cream",
    course: "dessert",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 1,
      western: 4,
      fish: 3,
      meat: 3,
      vegetable: 3,
      sweet: 4,
      spicy: 1,
      neutral: 2,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Sasa Dango",
    course: "dessert",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 1,
      japanese: 5,
      western: 2,
      fish: 2,
      meat: 1,
      vegetable: 4,
      sweet: 5,
      spicy: 1,
      neutral: 3,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Cream Cake",
    course: "dessert",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 2,
      western: 5,
      fish: 1,
      meat: 2,
      vegetable: 2,
      sweet: 5,
      spicy: 1,
      neutral: 4,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Herb Tea",
    course: "dessert",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 4,
      japanese: 1,
      western: 4,
      fish: 3,
      meat: 3,
      vegetable: 3,
      sweet: 2,
      spicy: 2,
      neutral: 2,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Strawberry Milk",
    course: "dessert",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 1,
      japanese: 2,
      western: 5,
      fish: 1,
      meat: 1,
      vegetable: 2,
      sweet: 4,
      spicy: 1,
      neutral: 4,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Breton Galette",
    course: "dessert",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 4,
      western: 3,
      fish: 1,
      meat: 2,
      vegetable: 3,
      sweet: 4,
      spicy: 1,
      neutral: 4,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Nanami Ice Cream",
    course: "dessert",
    difficulty: "A",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 2,
      western: 2,
      fish: 1,
      meat: 1,
      vegetable: 1,
      sweet: 1,
      spicy: 1,
      neutral: 1,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Fruit Parfait",
    course: "dessert",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 3,
      western: 3,
      fish: 1,
      meat: 3,
      vegetable: 3,
      sweet: 5,
      spicy: 1,
      neutral: 4,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Blueberry Pie",
    course: "dessert",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 2,
      western: 4,
      fish: 1,
      meat: 1,
      vegetable: 2,
      sweet: 5,
      spicy: 1,
      neutral: 4,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Dark Chocolate Cake",
    course: "dessert",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 2,
      western: 4,
      fish: 1,
      meat: 1,
      vegetable: 1,
      sweet: 4,
      spicy: 1,
      neutral: 3,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Mixed Fruit",
    course: "dessert",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 3,
      western: 3,
      fish: 2,
      meat: 2,
      vegetable: 3,
      sweet: 5,
      spicy: 1,
      neutral: 3,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Shooting Star",
    course: "dessert",
    difficulty: "A",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 3,
      western: 5,
      fish: 1,
      meat: 1,
      vegetable: 1,
      sweet: 5,
      spicy: 1,
      neutral: 5,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Chocolate Pizza",
    course: "dessert",
    difficulty: "C",
    surprise: true,
    rating: {
      chinese: 2,
      japanese: 2,
      western: 1,
      fish: 1,
      meat: 1,
      vegetable: 2,
      sweet: 5,
      spicy: 1,
      neutral: 2,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Cherry Pie",
    course: "dessert",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 2,
      western: 4,
      fish: 1,
      meat: 2,
      vegetable: 4,
      sweet: 5,
      spicy: 1,
      neutral: 4,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Golden Zucotto",
    course: "dessert",
    difficulty: "A",
    surprise: true,
    rating: {
      chinese: 3,
      japanese: 3,
      western: 5,
      fish: 1,
      meat: 1,
      vegetable: 2,
      sweet: 5,
      spicy: 1,
      neutral: 5,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },

  {
    dish: "Hot Sandwich",
    course: "main",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 3,
      western: 4,
      fish: 3,
      meat: 4,
      vegetable: 3,
      sweet: 3,
      spicy: 3,
      neutral: 3,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Hamburg Steak",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 3,
      western: 4,
      fish: 3,
      meat: 5,
      vegetable: 2,
      sweet: 3,
      spicy: 3,
      neutral: 4,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Salmon Steak",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 3,
      western: 4,
      fish: 5,
      meat: 2,
      vegetable: 2,
      sweet: 3,
      spicy: 3,
      neutral: 4,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Spring Roll",
    course: "main",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 5,
      japanese: 4,
      western: 3,
      fish: 3,
      meat: 3,
      vegetable: 4,
      sweet: 2,
      spicy: 4,
      neutral: 3,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Tlayuda",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 1,
      western: 2,
      fish: 3,
      meat: 4,
      vegetable: 4,
      sweet: 3,
      spicy: 4,
      neutral: 3,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Rabbit Stew",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 4,
      japanese: 1,
      western: 4,
      fish: 3,
      meat: 5,
      vegetable: 3,
      sweet: 2,
      spicy: 2,
      neutral: 2,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Ramen",
    course: "main",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 5,
      japanese: 4,
      western: 3,
      fish: 2,
      meat: 4,
      vegetable: 3,
      sweet: 3,
      spicy: 2,
      neutral: 4,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Cold Pasta",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 3,
      western: 5,
      fish: 2,
      meat: 2,
      vegetable: 4,
      sweet: 2,
      spicy: 1,
      neutral: 3,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Scallop Lunch Set",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 5,
      western: 2,
      fish: 4,
      meat: 2,
      vegetable: 2,
      sweet: 2,
      spicy: 2,
      neutral: 2,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Bang Bang Ji",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 4,
      japanese: 2,
      western: 2,
      fish: 2,
      meat: 1,
      vegetable: 4,
      sweet: 1,
      spicy: 5,
      neutral: 3,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Cold Noodles",
    course: "main",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 4,
      japanese: 4,
      western: 2,
      fish: 2,
      meat: 3,
      vegetable: 4,
      sweet: 2,
      spicy: 3,
      neutral: 4,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Ceviche Tostadas",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 1,
      japanese: 2,
      western: 5,
      fish: 4,
      meat: 1,
      vegetable: 2,
      sweet: 1,
      spicy: 1,
      neutral: 4,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Nanban Fish",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 4,
      western: 2,
      fish: 5,
      meat: 2,
      vegetable: 1,
      sweet: 1,
      spicy: 3,
      neutral: 3,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Spicy Hamburg Steak",
    course: "main",
    difficulty: "C",
    surprise: true,
    rating: {
      chinese: 4,
      japanese: 3,
      western: 3,
      fish: 2,
      meat: 5,
      vegetable: 2,
      sweet: 2,
      spicy: 5,
      neutral: 5,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Moonview Kebab",
    course: "main",
    difficulty: "B",
    surprise: true,
    rating: {
      chinese: 3,
      japanese: 2,
      western: 4,
      fish: 1,
      meat: 5,
      vegetable: 1,
      sweet: 1,
      spicy: 5,
      neutral: 5,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Tomato Sandwich",
    course: "main",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 2,
      western: 3,
      fish: 2,
      meat: 2,
      vegetable: 5,
      sweet: 2,
      spicy: 2,
      neutral: 4,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Sautéed Chicken",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 3,
      western: 3,
      fish: 2,
      meat: 5,
      vegetable: 1,
      sweet: 1,
      spicy: 3,
      neutral: 4,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Umeboshi Chazuke",
    course: "main",
    difficulty: "E",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 5,
      western: 1,
      fish: 3,
      meat: 2,
      vegetable: 5,
      sweet: 1,
      spicy: 2,
      neutral: 3,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Blue Impact Curry",
    course: "main",
    difficulty: "A",
    surprise: true,
    rating: {
      chinese: 2,
      japanese: 5,
      western: 3,
      fish: 1,
      meat: 3,
      vegetable: 2,
      sweet: 1,
      spicy: 3,
      neutral: 1,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Tom Yam Kung",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 5,
      japanese: 2,
      western: 3,
      fish: 1,
      meat: 5,
      vegetable: 4,
      sweet: 1,
      spicy: 5,
      neutral: 3,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Herb Chicken",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 3,
      western: 3,
      fish: 1,
      meat: 5,
      vegetable: 4,
      sweet: 1,
      spicy: 3,
      neutral: 4,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Maqluba",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 3,
      western: 4,
      fish: 2,
      meat: 3,
      vegetable: 5,
      sweet: 2,
      spicy: 2,
      neutral: 3,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Shrimp Doria",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 2,
      western: 5,
      fish: 4,
      meat: 3,
      vegetable: 1,
      sweet: 1,
      spicy: 4,
      neutral: 4,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Raclette",
    course: "main",
    difficulty: "A",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 2,
      western: 5,
      fish: 2,
      meat: 4,
      vegetable: 4,
      sweet: 3,
      spicy: 2,
      neutral: 3,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Mee Siam",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 4,
      japanese: 4,
      western: 3,
      fish: 2,
      meat: 2,
      vegetable: 3,
      sweet: 3,
      spicy: 3,
      neutral: 3,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Cheese Fondue",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 2,
      western: 4,
      fish: 3,
      meat: 3,
      vegetable: 4,
      sweet: 2,
      spicy: 2,
      neutral: 5,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Steak",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 4,
      japanese: 4,
      western: 4,
      fish: 2,
      meat: 5,
      vegetable: 2,
      sweet: 1,
      spicy: 2,
      neutral: 5,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Avocado Sushi",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 4,
      western: 4,
      fish: 3,
      meat: 1,
      vegetable: 5,
      sweet: 3,
      spicy: 2,
      neutral: 3,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Hummus",
    course: "main",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 3,
      western: 4,
      fish: 3,
      meat: 1,
      vegetable: 5,
      sweet: 3,
      spicy: 1,
      neutral: 3,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Fresh Spring Roll",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 5,
      japanese: 2,
      western: 3,
      fish: 4,
      meat: 4,
      vegetable: 4,
      sweet: 1,
      spicy: 2,
      neutral: 4,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Ahi Poke",
    course: "main",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 4,
      western: 2,
      fish: 5,
      meat: 1,
      vegetable: 5,
      sweet: 1,
      spicy: 2,
      neutral: 5,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Cold Pho",
    course: "main",
    difficulty: "D",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 5,
      western: 3,
      fish: 3,
      meat: 2,
      vegetable: 5,
      sweet: 1,
      spicy: 1,
      neutral: 4,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Shell-On Shrimp",
    course: "main",
    difficulty: "A",
    surprise: true,
    rating: {
      chinese: 5,
      japanese: 1,
      western: 1,
      fish: 5,
      meat: 2,
      vegetable: 1,
      sweet: 1,
      spicy: 5,
      neutral: 4,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Duck Soup",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 5,
      western: 1,
      fish: 1,
      meat: 5,
      vegetable: 4,
      sweet: 1,
      spicy: 1,
      neutral: 4,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Chili con Carne",
    course: "main",
    difficulty: "A",
    surprise: false,
    rating: {
      chinese: 5,
      japanese: 2,
      western: 2,
      fish: 1,
      meat: 4,
      vegetable: 4,
      sweet: 1,
      spicy: 5,
      neutral: 3,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Roast Beef",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 4,
      japanese: 4,
      western: 4,
      fish: 3,
      meat: 5,
      vegetable: 1,
      sweet: 1,
      spicy: 3,
      neutral: 5,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Curry",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 4,
      western: 3,
      fish: 1,
      meat: 4,
      vegetable: 4,
      sweet: 1,
      spicy: 5,
      neutral: 5,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Shark Fin Soup",
    course: "main",
    difficulty: "A",
    surprise: false,
    rating: {
      chinese: 5,
      japanese: 2,
      western: 3,
      fish: 5,
      meat: 3,
      vegetable: 3,
      sweet: 1,
      spicy: 3,
      neutral: 2,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Grilled Tutuva",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 4,
      japanese: 2,
      western: 3,
      fish: 2,
      meat: 5,
      vegetable: 1,
      sweet: 1,
      spicy: 1,
      neutral: 3,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Pineapple Pork",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 5,
      japanese: 1,
      western: 1,
      fish: 1,
      meat: 3,
      vegetable: 3,
      sweet: 4,
      spicy: 1,
      neutral: 2,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Deluxe Gyoza",
    course: "main",
    difficulty: "A",
    surprise: true,
    rating: {
      chinese: 5,
      japanese: 2,
      western: 2,
      fish: 4,
      meat: 4,
      vegetable: 4,
      sweet: 2,
      spicy: 2,
      neutral: 4,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Smørrebrød",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 2,
      western: 5,
      fish: 4,
      meat: 4,
      vegetable: 4,
      sweet: 1,
      spicy: 1,
      neutral: 5,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Brew Bar Satay",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 5,
      japanese: 3,
      western: 4,
      fish: 1,
      meat: 5,
      vegetable: 1,
      sweet: 1,
      spicy: 3,
      neutral: 5,
      uncommon: 5,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Pasta Carbonara",
    course: "main",
    difficulty: "C",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 3,
      western: 5,
      fish: 2,
      meat: 3,
      vegetable: 2,
      sweet: 3,
      spicy: 1,
      neutral: 4,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Dragon Doria",
    course: "main",
    difficulty: "A",
    surprise: true,
    rating: {
      chinese: 4,
      japanese: 4,
      western: 4,
      fish: 2,
      meat: 5,
      vegetable: 1,
      sweet: 1,
      spicy: 2,
      neutral: 5,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Triple Burger",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 3,
      japanese: 2,
      western: 4,
      fish: 1,
      meat: 5,
      vegetable: 3,
      sweet: 1,
      spicy: 2,
      neutral: 5,
      uncommon: 2,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Galactic Meat",
    course: "main",
    difficulty: "A",
    surprise: true,
    rating: {
      chinese: 4,
      japanese: 3,
      western: 4,
      fish: 2,
      meat: 5,
      vegetable: 1,
      sweet: 1,
      spicy: 4,
      neutral: 5,
      uncommon: 1,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Nigiri Selection",
    course: "main",
    difficulty: "B",
    surprise: false,
    rating: {
      chinese: 2,
      japanese: 5,
      western: 1,
      fish: 5,
      meat: 1,
      vegetable: 3,
      sweet: 1,
      spicy: 1,
      neutral: 3,
      uncommon: 3,
      everything: 4,
      nothing: 1,
    },
  },
  {
    dish: "Osechi",
    course: "main",
    difficulty: "A",
    surprise: false,
    rating: {
      chinese: 1,
      japanese: 5,
      western: 2,
      fish: 3,
      meat: 3,
      vegetable: 3,
      sweet: 3,
      spicy: 3,
      neutral: 4,
      uncommon: 4,
      everything: 4,
      nothing: 1,
    },
  },
];

const judge_data = [
  { judge: "Aire", preference: "fish", favorite: "Nanban Fish" },
  { judge: "Aleior", preference: "fish", favorite: "Shooting Star" },
  { judge: "Allaby", preference: "spicy", favorite: "Spicy Hamburg Steak" },
  { judge: "Alwe", preference: "meat", favorite: "Grilled Tutuva" },
  { judge: "Aoi", preference: "sweet", favorite: "Sasa Dango" },
  { judge: "B'baba", preference: "chinese", favorite: "Shark Fin Soup" },
  { judge: "Barnard", preference: "spicy", favorite: "Spiced Coffee" },
  { judge: "Cabana", preference: "japanese", favorite: "Strawberry Milk" },
  { judge: "Caine", preference: "vegetable", favorite: "Vegetable Milk Soup" },
  { judge: "Carrie", preference: "fish", favorite: "Shrimp Doria" },
  { judge: "Cassandra", preference: "neutral", favorite: "Herb Tea" },
  { judge: "Celia", preference: "japanese", favorite: "Fried Egg" },
  { judge: "Chandra", preference: "fish", favorite: "Apple Cider Soda" },
  { judge: "Chron", preference: "spicy", favorite: "Shooting Star" },
  { judge: "CJ", preference: "meat", favorite: "Galactic Meat" },
  { judge: "Clarke", preference: "neutral", favorite: "Herb Tea" },
  { judge: "Code L", preference: "sweet", favorite: "Mint Chip Ice Cream" },
  { judge: "Dalton", preference: "spicy", favorite: "Spicy Hamburg Steak" },
  { judge: "Dijkstra", preference: "spicy", favorite: "Tom Yam Kung" },
  { judge: "Douglas", preference: "western", favorite: "Pasta Carbonara" },
  { judge: "Dr. Corque", preference: "sweet", favorite: "Baumkuchen" },
  { judge: "Durlan", preference: "spicy", favorite: "Tom Yam Kung" },
  { judge: "El Alicanto", preference: "meat", favorite: "Tlayuda" },
  { judge: "Elektra", preference: "chinese", favorite: "Shark Fin Soup" },
  { judge: "Enoe", preference: "vegetable", favorite: "Bang Bang Ji" },
  { judge: "Euma", preference: "everything", favorite: "Cherry Pie" },
  { judge: "Falward", preference: "japanese", favorite: "Hamburg Steak" },
  { judge: "Faye", preference: "uncommon", favorite: "Deluxe Gyoza" },
  { judge: "Foxiel", preference: "western", favorite: "Vegetable Milk Soup" },
  { judge: "Francesca", preference: "chinese", favorite: "Galactic Meat" },
  { judge: "Frida", preference: "sweet", favorite: "Lollipop" },
  { judge: "Fume", preference: "vegetable", favorite: "Maqluba" },
  { judge: "Galdorf", preference: "fish", favorite: "Smørrebrød" },
  { judge: "Galladur", preference: "vegetable", favorite: "Spinach Quiche" },
  { judge: "Garoo", preference: "sweet", favorite: "Pavlova" },
  { judge: "Garr", preference: "sweet", favorite: "Pancakes" },
  { judge: "Gieran", preference: "sweet", favorite: "Cream Cake" },
  { judge: "Gigina", preference: "chinese", favorite: "Pineapple Pork" },
  { judge: "Glen", preference: "neutral", favorite: "Dragon Doria" },
  { judge: "Gocteau", preference: "meat", favorite: "Steak" },
  { judge: "Goldsmid", preference: "vegetable", favorite: "Tiger Salad" },
  { judge: "Goldwyn", preference: "western", favorite: "Shrimp Doria" },
  { judge: "Hakugin", preference: "sweet", favorite: "Baked Flan" },
  { judge: "Hildi", preference: "sweet", favorite: "Sugar Toast" },
  { judge: "Hiro", preference: "chinese", favorite: "Mint Chip Ice Cream" },
  { judge: "Hogan", preference: "fish", favorite: "Salmon Steak" },
  { judge: "Huang", preference: "japanese", favorite: "Miso Soup" },
  { judge: "Iris", preference: "western", favorite: "Black Tea Cookies" },
  { judge: "Isha", preference: "spicy", favorite: "Tom Yam Kung" },
  { judge: "Iugo", preference: "japanese", favorite: "Umeboshi Chazuke" },
  { judge: "Ivy", preference: "western", favorite: "Strawberry Milk" },
  { judge: "Janquis", preference: "fish", favorite: "Marinated Seafood" },
  { judge: "Jorhan", preference: "japanese", favorite: "Steak" },
  { judge: "Kallathor", preference: "vegetable", favorite: "Chopan Salad" },
  { judge: "Kassius", preference: "meat", favorite: "Moonview Kebab" },
  { judge: "Kerrin", preference: "sweet", favorite: "Lemon Honey Pickles" },
  { judge: "Kogen", preference: "japanese", favorite: "Nigiri Selection" },
  { judge: "Kuroto", preference: "meat", favorite: "Rabbit Stew" },
  { judge: "Lakían", preference: "vegetable", favorite: "Vegetable Milk Soup" },
  { judge: "Lam", preference: "neutral", favorite: "Mee Siam" },
  { judge: "Larla", preference: "japanese", favorite: "Avocado Sushi" },
  { judge: "Leene", preference: "sweet", favorite: "Pancakes" },
  { judge: "Leon", preference: "neutral", favorite: "Hot Sandwich" },
  { judge: "Lian", preference: "spicy", favorite: "Spicy Hamburg Steak" },
  { judge: "Lilwn", preference: "sweet", favorite: "Lemon Honey Pickles" },
  { judge: "Mandie", preference: "vegetable", favorite: "Vegetable Juice" },
  { judge: "Mariette", preference: "western", favorite: "Cherry Pie" },
  { judge: "Marin", preference: "vegetable", favorite: "Gazpacho" },
  { judge: "Marisa", preference: "sweet", favorite: "Herb Chicken" },
  { judge: "Markus", preference: "neutral", favorite: "Jelly Beans" },
  { judge: "Martha", preference: "spicy", favorite: "Moonview Kebab" },
  { judge: "Maureus", preference: "meat", favorite: "Sautéed Chicken" },
  { judge: "Maxim", preference: "meat", favorite: "Roast Beef" },
  { judge: "Mellore", preference: "sweet", favorite: "Cream Cake" },
  { judge: "Melridge", preference: "chinese", favorite: "Duck Soup" },
  { judge: "Mihlu", preference: "fish", favorite: "Blueberry Pie" },
  { judge: "Milana", preference: "chinese", favorite: "Hamburg Steak" },
  { judge: "Mio", preference: "japanese", favorite: "Sasa Dango" },
  { judge: "Momo", preference: "nothing", favorite: "Fruit Parfait" },
  { judge: "Nell", preference: "sweet", favorite: "Cream Cake" },
  { judge: "Nil", preference: "nothing", favorite: "Baked Flan" },
  { judge: "Ormond", preference: "western", favorite: "Omelet" },
  { judge: "Paquia", preference: "sweet", favorite: "Steamed Bread" },
  { judge: "Pastole", preference: "meat", favorite: "Brew Bar Satay" },
  { judge: "Perrielle", preference: "neutral", favorite: "Tomato Sandwich" },
  { judge: "Pieter", preference: "everything", favorite: "Jelly Beans" },
  { judge: "Pohl", preference: "western", favorite: "Pot-au-feu" },
  { judge: "Prunella", preference: "japanese", favorite: "Duck Soup" },
  { judge: "Quinn", preference: "western", favorite: "Raclette" },
  { judge: "Reid", preference: "neutral", favorite: "Brew Bar Satay" },
  { judge: "Reyna", preference: "meat", favorite: "Hamburg Steak" },
  { judge: "Riufan", preference: "chinese", favorite: "Spring Roll" },
  { judge: "Rody", preference: "neutral", favorite: "Pretzel" },
  { judge: "Rohan", preference: "fish", favorite: "Nigiri Selection" },
  { judge: "Rudy", preference: "chinese", favorite: "Deluxe Gyoza" },
  { judge: "Sabine", preference: "spicy", favorite: "Spicy Pig's Ear" },
  { judge: "Scarlet", preference: "spicy", favorite: "Fresh Spring Roll" },
  { judge: "Seign", preference: "western", favorite: "Poached Egg" },
  { judge: "Selbineth", preference: "fish", favorite: "Shell-On Shrimp" },
  { judge: "Shixeen", preference: "spicy", favorite: "Tomato Sandwich" },
  { judge: "Skyd", preference: "fish", favorite: "Avocado Sushi" },
  { judge: "Squash", preference: "vegetable", favorite: "Spinach Quiche" },
  { judge: "Stadler", preference: "spicy", favorite: "Chili con Carne" },
  { judge: "Sumire", preference: "western", favorite: "Cheese Fondue" },
  { judge: "Syd", preference: "neutral", favorite: "Cheese on Crackers" },
  { judge: "Valentin", preference: "sweet", favorite: "Dark Chocolate Cake" },
  { judge: "Viesskin", preference: "uncommon", favorite: "Chocolate Pizza" },
  { judge: "Vorrdice", preference: "meat", favorite: "Roast Beef" },
  { judge: "Wayve", preference: "neutral", favorite: "Lollipop" },
  { judge: "Wyler", preference: "vegetable", favorite: "Vegetable Juice" },
  { judge: "Yaelu", preference: "western", favorite: "Blueberry Pie" },
  { judge: "Ymir", preference: "vegetable", favorite: "Vegetable Juice" },
  { judge: "Yuferius", preference: "japanese", favorite: "Avocado Sushi" },
  { judge: "Yulin", preference: "sweet", favorite: "Mixed Fruit" },
  { judge: "Yume", preference: "japanese", favorite: "Fried Egg" },
  { judge: "Yusuke", preference: "meat", favorite: "Hamburg Steak" },
  { judge: "Yuthus", preference: "chinese", favorite: "Bang Bang Ji" },
  { judge: "Zabi", preference: "japanese", favorite: "Miso Soup" },
];

const cusine_data = {
  chinese: { icon: "🥡", name: "Chinese" },
  japanese: { icon: "🍣", name: "Japanese" },
  western: { icon: "🍔", name: "Western" },
  fish: { icon: "🐟", name: "Fish" },
  meat: { icon: "🍖", name: "Meat" },
  vegetable: { icon: "🥦", name: "Vegetable" },
  sweet: { icon: "🍬", name: "Sweet" },
  spicy: { icon: "🌶️", name: "Spicy" },
  neutral: { icon: "🍞", name: "Neutral" },
  uncommon: { icon: "🦄", name: "Uncommon" },
  everything: { icon: "😋", name: "Everything" },
  nothing: { icon: "🤢", name: "Nothing" },
};
